# Schema for the configuration form.
custom_rest_api.settings:
  type: config_object
  label: 'API Key'
  mapping:
    # creating schema by using field name (apikey).
    api_key:
      label: 'API Key'
      type: text